format
    ACTIVITY                  D00083F.
    DURATION                  M00840F.
    DUR_03                    A00708F.
    ENDMIN                    M00839F.
    ENDTIME                  $M00839F.
    INSTANCE                  M00077F.
    LOCATION                  D00085F.
    PUMFID                    M00087F.
    STARTIME                 $M00839F.
    STARTMIN                  M00839F.
    TUI_01                    D00140F.
    TUI_03                    D00141F.
    TUI_06A                   YESN01F.
    TUI_06B                   YESN01F.
    TUI_06C                   YESN01F.
    TUI_06D                   YESN01F.
    TUI_06E                   YESN01F.
    TUI_06F                   YESN01F.
    TUI_06G                   YESN01F.
    TUI_06H                   YESN01F.
    TUI_06I                   YESN01F.
    TUI_06J                   YESN01F.
    TUI_07                    YESN01F.
    TUI_15                    A00709F.
    WEPI_001                  M00835F.
    WGHT_EPI                  M00834F.
    ;
