label variable PUMFID    "PUMF Record identification"
label variable INSTANCE  "Sequential episode number"
label variable WGHT_EPI  "Episode weight"
label variable ACTIVITY  "Main activity"
label variable DUR_03    "Length of the simultaneous activity"
label variable DURATION  "Duration of an episode (in minutes)"
label variable ENDMIN    "End time of the episode in minutes"
label variable ENDTIME   "End time of the episode"
label variable INSTANCE  "Sequential episode number"
label variable LOCATION  "Location of the episode"
label variable STARTIME  "Start time of the episode"
label variable STARTMIN  "Start time of the episode in minutes"
label variable TUI_01    "Main activity - Detailed level codes"
label variable TUI_03    "Simultaneous activity"
label variable TUI_06A   "Social contact - Alone"
label variable TUI_06B   "Social contact - With spouse/partner"
label variable TUI_06C   "Social contact - With household children, less than 15 years old"
label variable TUI_06D   "Social contact - With household child(ren), 15 years or older"
label variable TUI_06E   "Social contact - With parent(s) or parent(s)-in-law"
label variable TUI_06F   "Social contact - With other household adult(s)"
label variable TUI_06G   "Social contact - With other family member(s) from other households"
label variable TUI_06H   "Social contact - With friends"
label variable TUI_06I   "Social contact - With colleague(s), classmate(s)"
label variable TUI_06J   "Social contact - With other people"
label variable TUI_07    "Respondent use of technology"
label variable TUI_15    "Subjective well-being scale"
label variable WEPI_001  "Bootstrap weight # 1 at the episode level"
