label variable PUMFID    "Numéro d’identification de l’enregistrement du FMGD"
label variable WGHT_PER  "Pondération de la personne"
label variable SURVMNTH  "Mois de l’enquête"
label variable EQFLAG    "Mode de collecte de l’enquête"
label variable PRV       "Province de résidence"
label variable LUC_RST   "Indicateur des centres de population"
label variable REGION    "Région de résidence du répondant"
label variable HSDSIZEC  "Taille du ménage du répondant (plafonnée)"
label variable AGEGR10   "Groupe d’âge du répondant (groupes de 10)"
label variable GENDER2   "Genre (2) après distribution des personnes non binaires"
label variable MARSTAT   "État matrimonial du répondant"
label variable PHSDFLG   "Répondant a un(e) conjoint(e)/partenaire dans le ménage"
label variable AGEPRC    "Groupe d'âge du conjoint(e)/partenaire du répondant (regroupée)"
label variable GENPR2    "Genre du/de la contoint(e) après distribution des pers. non binaires"
label variable COUPGEN2  "Genre+ du couple dans le ménage"
label variable CHH0017C  "Nombre d’enfants dans le ménage - 0 à 17 ans (plafonné)"
label variable CHH0004C  "Enfants dans le ménage - 0 à 4 ans (indicateur)"
label variable CHH0514C  "Enfants dans le ménage - 5 à 14 ans (indicateur)"
label variable CHH1517C  "Enfants dans le ménage - 15 à 17 ans (indicateur)"
label variable CXRFLAG   "Enfant(s) du répondant vivant dans le ménage"
label variable PARNUM    "Nombre de parents du répondant dans le ménage"
label variable SENFLAG   "Personne(s) âgée(s) de 65 ans et plus dans le ménage"
label variable MULTIGEN  "Trois générations et plus dans le ménage du répondant"
label variable DDEV_FL   "Indicateur d’incapacité - Développement"
label variable DDEX_FL   "Indicateur d’incapacité - Dextérité"
label variable DFLEX_FL  "Indicateur d’incapacité - Flexibilité"
label variable DHEAR_FL  "Indicateur d’incapacité - Ouïe"
label variable DLRN_FL   "Indicateur d’incapacité - Apprentissage"
label variable DMEM_FL   "Indicateur d’incapacité - Mémoire"
label variable DMENT_FL  "Indicateur d’incapacité - Santé mentale"
label variable DMOB_FL   "Indicateur d’incapacité - Mobilité"
label variable DPAIN_FL  "Indicateur d’incapacité - Douleur"
label variable DUNK_FL   "Indicateur d’incapacité - Incapacité inconnue"
label variable DVIS_FL   "Indicateur d’incapacité - Vision"
label variable DDIS_FL   "Statut d’incapacité"
label variable DTYPER    "Nombre de types d’incapacité - Regroupé"
label variable DCLASS    "Classe globale de sévérité (de l’incapacité)"
label variable TCS_110   "Perceptions du temps - Planifie ralentir le rythme"
label variable TCS_120   "Perceptions du temps - Bourreau de travail"
label variable TCS_130   "Perceptions du temps - Porté à réduire les heures de sommeil"
label variable TCS_140   "Perceptions du temps-N’avez pas accompli ce que vous vouliez accomplir"
label variable TCS_150   "Perceptions du temps -Pas assez de temps consacré à la famille ou amis"
label variable TCS_160   "Perceptions du temps - Constamment tendu"
label variable TCS_170   "Perceptions du temps - Pris dans une routine quotidienne"
label variable TCS_180   "Perceptions du temps - Pas de temps pour s’amuser"
label variable TCS_190   "Perceptions du temps - Se sentir tendu par manque de temps"
label variable TCS_200   "Perceptions du temps - Aimerait passer plus de temps seul"
label variable TIMECR    "Indicateur de pressé par le temps"
label variable UH_01     "Service non rémunéré - À vous occuper des enfants de votre ménage"
label variable UH_02     "Service non rémunéré - À vous occuper des enfants d’autres ménages"
label variable UH_03     "Service non rémunéré - Tâches domestiques pour votre ménage"
label variable UH_04     "Service non rémunéré - Tâches domestiques pour d’autres ménages"
label variable UH_05     "Service non rémunéré - Soins à des personnes âgées du ménage"
label variable UH_06     "Service non rémunéré - Soins à des personnes âgées d’autres ménages"
label variable CHLD_01C  "Soins des enfants - Jour de semaine - Soins physiques (regroupement)"
label variable CHLD_02C  "Soins des enfants - Jour de semaine - Liés à l’école (regroupement)"
label variable CHLD_03C  "Soins des enfants - Jour de semaine - Activités de loisirs (regroupeme"
label variable CHLD_04C  "Soins des enfants - Jour de semaine - Accompagner (regroupement)"
label variable CHLD_05C  "Soins des enfants - Fin de semaine - Soins physiques (regroupement)"
label variable CHLD_06C  "Soins des enfants - Fin de semaine - Liés à l’école (regroupement)"
label variable CHLD_07C  "Soins des enfants - Fin de semaine - Activités de loisirs (regroupemen"
label variable CHLD_08C  "Soins des enfants - Fin de semaine - Accompagner (regroupement)"
label variable LSM_01    "Bien-être subjectif"
label variable GEN_01    "État de santé autodéclaré"
label variable GEN_02    "État de santé mentale autodéclaré"
label variable SRS_10    "Niveau de stress autodéclaré - Niveau"
label variable MSS_130   "Source Principale de stress"
label variable ACT7DAYC  "Activité principale - La semaine dernière (regroupement)"
label variable MRW_05C   "Activité principale - 12 derniers mois (regroupement)"
label variable MRW_D40A  "Travaillait l’année dernière"
label variable MRW_D40B  "Travaillait la semaine dernière"
label variable WET_120   "Type d’emploi pendant les semaines travaillées"
label variable WHW_110   "Plus d’un emploi rémunéré la semaine dernière"
label variable WHW_230   "Horaire de travail habituel à l’emploi principal"
label variable WHWD140G  "Nombre d’heures travaillées ­tout emploi par semaine (regroupée)"
label variable TLWK_01A  "Télétravail la semaine dernière - À la maison"
label variable TLWK_01B  "Télétravail la semaine dernière - Dans un espace de travail partagé"
label variable TLWK_01C  "Télétravail la semaine dernière - Autre endroit"
label variable TLWK_01D  "Télétravail la semaine dernière - N’avait pas fait de télétravail"
label variable TLWK_02G  "Télétravail la semaine dernière - Heures de travail rémunéré (regroupé"
label variable TLWK_03   "Quantité préférée de télétravail dans l'horaire de travail"
label variable TLWK_04   "Aspects du télétravail - Organiser son propre horaire de travail"
label variable TLWK_05   "Aspects du télétravail - La vidéoconférence"
label variable TLWK_06   "Aspects du télétravail - Éviter les aller-retour"
label variable TLWK_07   "Aspects du télétravail - Réduire le nombre de voyages d'affaires"
label variable TLWK_08   "Asp. du télétrav. Passer du temps avec la fam., l'animal de compagnie"
label variable TLWK_09   "Raison de ne pas avoir fait du télétravail la semaine dernière"
label variable WLYD170G  "Distance entre le domicile et le lieu de travail (regroupée)"
label variable NAIC22CY  "SCIAN 2022 (20 catégories) - L’an dernier"
label variable NOCLBR_Y  "CNP 21 (10 catégories) - L’an dernier (la vairante)"
label variable WFS_10    "Horaire de travail flexible"
label variable SRC_10    "Satisfaction par rapport à l’équilibre travail-vie à la maison"
label variable SRC_20A   "Insatisfaction - Travail/maison - Pas assez de temps à la famille"
label variable SRC_20B   "Insatisfaction - Travail/maison - Trop de temps à l’emploi/act. prin."
label variable SRC_20C   "Insatisfaction - Travail/maison - Pas assez de temps autres activités"
label variable SRC20EGR  "Insatisfaction - Travail/maison - Raisons liées à l’emploi (regroupée)"
label variable SRC_20F   "Insatisfaction - Travail/maison - Raisons de santé"
label variable SRC20HGR  "Insatisfaction - Travail/maison - Autre (regroupé)"
label variable WLB_10    "Équilibre travail-vie - Difficulté en raison du travail - 12 mois"
label variable WLB_20    "Équilibre travail-vie - Difficulté en raison de la famille - 12 mois"
label variable HRH_10A   "Embauche l’aide rémunéré - Aucun"
label variable HRH_10B   "Embauche l’aide rémunéré - Service de garde"
label variable HRH_10C   "Embauche l’aide rémunéré - Nettoyage de la maison"
label variable HRH_10D   "Embauche l’aide rémunéré - Travaux extérieurs"
label variable HRH_10E   "Embauche l’aide rémunéré - Soins médicaux"
label variable HRH_10F   "Embauche l’aide rémunéré - Autre"
label variable ATT_120   "Un véhicule à la disposition du répondant"
label variable ATT_130   "A besoin d'une autre personne pour conduire - Fréquence"
label variable ATT_131   "Quelqu'un peut conduire le répondant quand requis - Fréquence"
label variable ATT_140A  "Conduire si requis - Membre de la famille, habite avec le répondant"
label variable ATT_140B  "Conduit si requis-Membre de la famille, n'habite pas avec le répondant"
label variable ATT_140C  "Conduire si requis - Ami"
label variable ATT_140D  "Conduire si requis - Voisin"
label variable ATT_140E  "Conduire si requis - Organization ou agence"
label variable ATT_150C  "Type de transport plus courant - Semain typique (regroupement)"
label variable ATT_160   "Accès au transport en commun"
label variable ATT_170   "Utilisation du transport en commun - 12 derniers mois"
label variable ATT_180A  "N'utilise pas transport en commun - Vous possédez une auto"
label variable ATT_180B  "N'utilise pas transport en commun - Se déplace à pied ou à vélo"
label variable ATT_180C  "N'utilise pas transport en commun - Préoccupation pour votre santé"
label variable ATT_180D  "N'utilise pas transport en commun - Les arrêts sont trop loin"
label variable ATT_180E  "N'utilise pas transport en commun - L’horaire ne convient pas"
label variable ATT_180F  "N'utilise pas transport en commun - Les circuits ne conviennent pas"
label variable ATT_180G  "N'utilise pas transport en commun - Une incapacité vous en empêche"
label variable ATT_180I  "N'utilise pas trans. en commun - Stationnement disponible au travail"
label variable ATT_180J  "N'utilise pas transport en commun - Préoccupation pour votre sécurité"
label variable CTW_140A  "Transport au travail/école - Voiture, camion, fourgonnette -Conducteur"
label variable CTW_140B  "Transport au travail/école  - Voiture, camion, fourgonnette - Passager"
label variable CTW_140C  "Transport au travail/école - Transport en commun"
label variable CTW_140D  "Transport au travail/école - À pied"
label variable CTW_140E  "Transport au travail/école - Bicyclette"
label variable CTW140GR  "Transport au travail/école - Autre façon (regroupé)"
label variable CTW_140I  "Transport au travail/school - Vous travailliez/étudiez de la maison"
label variable CTW_150G  "Transport au travail/école - Durée à sens unique (regroupé)"
label variable CTW_160   "Transport au travail/école - Déjà utilisé transport en commun"
label variable CTW_170   "Transport  - Avantage du transport en commun (utilisateur/trice)"
label variable CTW_180   "Transport - Avantage du transport en commun (non utilisateur/trice)"
label variable CTW_190   "Transport au travail/école - Congestion de la circulation (fréquence)"
label variable CTW_210   "Transport au travail/école - Satisfaction avec durée du trajet"
label variable CTW_215   "Transport au travail/école - Congestion de la circulation (sérieux)"
label variable ED_05     "Niveau de scolarité-Plus haut niveau d’études primaires ou secondaires"
label variable EDC_10    "Éducation - Fréquentation scolaire"
label variable MAP_110C  "Activité principale - Conjoint - 12 mois (regroupement)"
label variable MAP_D40A  "Conjoint(e) - Travaillait l’année dernière"
label variable DOR_110C  "Logement du répondant (regroupement)"
label variable IM_01A    "Né(e) au Canada/extérieur du Canada - Répondant"
label variable YRARRI_C  "Année où le répondant est venu au Canada pour la première fois (regrou"
label variable BPP_01A   "Lieu de naissance du conjoint/partenaire - Canada"
label variable BPR_20    "Parents nés au Canada ou à l'extérieur du Canada"
label variable ABM_01A   "Identité autochtone - N’est pas Première Nation, Métis ou Inuk (Inuit)"
label variable AIP_01A   "Identité autochtone du conjoint - N’est pas autochtone"
label variable VISMINFL  "Indicateur de minorité visible"
label variable VISPRFL   "Statut de minorité visible - Conjoint(e)/ partenaire du répondant"
label variable REL_02    "Fréquence participation à des activités religieuses - 12 derniers mois"
label variable REL_03    "Fréquence participation activités religieuses - Individuelle - 12 mois"
label variable RELIGFLG  "Indicateur d’appartenance religieuse"
label variable LAN_01    "Connaissance des langues officielles (français et anglais)"
label variable LANCHC    "Langue maternelle (regroupement)"
label variable LANHSDC   "Langue parlée le plus souvent à la maison (regroupement)"
label variable INC_C     "Revenu - Total (avant impôt) (regroupé)"
label variable FAMINC_C  "Revenu de la famille - Total (avant impôt) (regroupé)"
label variable GTU_110   "Emploi du temps général - Pressé par le temps"
label variable GTU_130   "Emploi du temps général - Temps libre"
label variable UOT_01    "Satisfaction avec l'usage du temps"
label variable DDAY      "Journal - Journée de référence"
label variable DVTDAY    "Journal - Journée de référence - Type"
label variable DIARYREC  "Période de rappel pour les journaux remplis"
label variable DUR101    "Durée - Sommeil essentiel (de nuit ou de jour)"
label variable DUR102    "Durée - Insomnie"
label variable DUR103    "Durée - Sieste, repos, se reposer, se détendre"
label variable DUR104    "Durée - Malade au lit, repos au lit ou de rééducation, convalescence"
label variable DUR109    "Durée - Sommeil/se détendre/repos au lit, non spécifié"
label variable DUR126    "Durée - Soins personnels"
label variable DUR127    "Durée - Soins médicaux auto-administrés"
label variable DUR128    "Durée - Soins de santé professionnels, consultation"
label variable DUR129    "Durée - Recevoir des soins personnels par un autre membre du ménage"
label variable DUR130    "Durée - Recevoir des soins personnels par fournisseurs de soins"
label variable DUR151    "Durée - Manger"
label variable DUR152    "Durée - Boire autrement qu'avec un repas ou une collation"
label variable DUR153    "Pause ou repas lié aux activités de travail rémunéré"
label variable DUR154    "Durée - Pause ou repas lié aux activités d'études ou d'apprentissage"
label variable DUR159    "Durée - Manger ou boire, non spécifié"
label variable DUR199    "Durée - Soins personnels, non spécifiés"
label variable DUR201    "Durée - Préparer ou servir les repas ou collations"
label variable DUR202    "Durée - Nettoyage après les repas, laver la vaisselle"
label variable DUR203    "Durée - Conservation de la nourriture"
label variable DUR204    "Durée - Déballer l'épicerie"
label variable DUR205    "Durée - Nettoyage intérieur domicile, ramasser, s'occuper des plantes"
label variable DUR206    "Durée - Sortir les poubelles, compost, recyclage ou déballage de biens"
label variable DUR207    "Durée - Lavage, rapiécer, repasser, soins des souliers, etc."
label variable DUR208    "Durée - Organiser, planifier activités mén., payer factures,  courrier"
label variable DUR209    "Durée - Soins des animaux de compagnie"
label variable DUR231    "Durée - Confection de vêtements (pour soi-même ou mén. ou fam.)"
label variable DUR232    "Durée - Travaux intérieurs d’entretien ou réparation faits soi-même"
label variable DUR233    "Durée - Installation, entretien ou réparation des biens matériels"
label variable DUR234    "Durée - Faire ou défaire les bagages pour un voyage ou le camping"
label variable DUR235    "Durée - Emballer ou déballer les boîtes pour un déménagement"
label variable DUR236    "Durée - Entretien extérieur"
label variable DUR237    "Durée - Travaux extérieurs d'entretien ou réparation faits soi-même"
label variable DUR238    "Durée - Construction faite soi-même"
label variable DUR239    "Durée - Entretien et réparation d'un véhicule"
label variable DUR240    "Durée - Ramasser, couper, corder du bois"
label variable DUR241    "Durée - Jardinage, faire l’élevage d’animaux, etc., pour le ménage"
label variable DUR261    "Durée - Magasinage de biens - en personne"
label variable DUR262    "Durée - Magasinage de services - en personne"
label variable DUR263    "Durée - Magasinage en ligne de biens ou services"
label variable DUR264    "Durée - Recherche pour faire l'achat de biens ou services"
label variable DUR269    "Durée - Magasinage, non spécifié"
label variable DUR299    "Durée - Tâches ménagères (mén. ou famille), non spécifié"
label variable DUR301    "Durée - Soins d'enfants (<15) (mén. ou fam.): Soins personnels"
label variable DUR302    "Durée - Soins d'enfants (<15) (mén. ou fam.): Lire, jouer"
label variable DUR303    "Durée - Soins d'enfants (<15) (mén. ou fam.): Éducatif"
label variable DUR304    "Durée - Soins d'enfants (<15) (mén. ou fam.) : Accompagnement"
label variable DUR305    "Durée - Soins d'ado (15-17) (mén. ou fam.) : Soins personnels"
label variable DUR306    "Durée - Soins d'ado. (15-17) (mén. ou fam.) : Éducatif"
label variable DUR307    "Durée - Soins d'ado (15-17) (mén. ou fam.) : Accompagnement"
label variable DUR351    "Durée - Soins d'adulte (18+) (mén. ou fam.) : Soins personnels"
label variable DUR352    "Durée - Soins d'adulte (18+) (mén. ou fam.) : Accompagnement"
label variable DUR353    "Durée - Soins d'adulte (18+) (mén. ou fam.) : Tâches ménagères"
label variable DUR359    "Durée - Prendre soin des adultes (18+) (mén. ou famille), non spécifié"
label variable DUR399    "Durée - Prendre soin des enfants (<18) (mén. ou fam.), non spécifié"
label variable DUR401    "Durée - Transport pour recevoir des soins personnels ou en revenir"
label variable DUR402    "Durée - Transport associé aux soins des enfants (<18) (mén. ou fam.)"
label variable DUR403    "Durée - Transport associé aux soins des adultes (18+) (mén. ou fam.)"
label variable DUR404    "Durée - Transport pour aller ou revenir de manger ou boire"
label variable DUR405    "Durée - Transport associé aux tâches ménagères régulières"
label variable DUR406    "Durée - Transport associé aux tâches ménagères occasionnelles"
label variable DUR407    "Durée - Transport pour se rendre ou revenir d'un travail rémunéré"
label variable DUR408    "Durée - Transport liées aux études ou à l'apprentissage"
label variable DUR409    "Durée - Transport pour se rendre ou revenir d'activités de magasinage"
label variable DUR410    "Durée - Transport lié aux activités de  socialisation ou communication"
label variable DUR411    "Durée - Transport bénévolat et autre travail non rémunéré"
label variable DUR412    "Durée - Transport activités citoyennes, religieuses ou communautaires"
label variable DUR413    "Durée - Transport lié aux sports ou à l'exercice"
label variable DUR414    "Durée - Transport lié aux activités culturelles, événements sportifs"
label variable DUR415    "Durée - Transport lié aux passe-temps, loisirs, activités extérieures"
label variable DUR416    "Durée - Transport associé à des activités liées aux médias de masse"
label variable DUR499    "Durée - Transport, non spécifié"
label variable DUR501    "Durée - Travail rémunéré"
label variable DUR502    "Durée - Formation rémunérée"
label variable DUR503    "Durée - Temps d'attente ou d'inactivité lié au travail rémunéré"
label variable DUR504    "Durée - Vente de biens ou de services contre rémunération ou profit"
label variable DUR505    "Durée - Autres activités générant des revenus"
label variable DUR506    "Durée - Recherche d'emploi"
label variable DUR599    "Durée - Travail rémunéré et autres activités reliées, non specifiés"
label variable DUR601    "Durée - Études à temps plein ou temps partiel - sur place"
label variable DUR602    "Durée - Études à temps plein ou temps partiel - en ligne"
label variable DUR603    "Durée - Travaux, devoirs, leçons ou recevoir du tutorat"
label variable DUR604    "Durée - Cours développement personnel, loisir ou intérêt particulier"
label variable DUR699    "Durée - Études ou apprentissage, non specifiés"
label variable DUR701    "Durée - Socialiser ou communiquer - en personne"
label variable DUR702    "Durée - Socialiser ou communiquer - en utilisant tout type technologie"
label variable DUR799    "Durée - Socialiser ou communiquer, non specifié"
label variable DUR801    "Durée -Aide non rémunérée (autre mém., pas fam.) -soins d'enfant (<18)"
label variable DUR802    "Durée - Aide non rémunérée (autre mém., pas fam.) - soins d'adulte"
label variable DUR803    "Durée - Aide non rémunérée (autre mém., pas fam.) - tâches ménagères"
label variable DUR804    "Durée - Travail non rémunéré dans une entreprise d'un autre ménage"
label variable DUR805    "Durée - Travail non rémunéré comme entraîneur, administrateur de sport"
label variable DUR806    "Durée - Bénévolat organisé  (travail non rémunéré, non obligatoire)"
label variable DUR807    "Durée - Travail non rémunéré visant à améliorer la communauté"
label variable DUR808    "Durée - Travail non rémunéré exigé école,  employeur, tribunal, autre"
label variable DUR899    "Durée - Travail non-rém. pas pour son mén., non spécifié"
label variable DUR901    "Durée - Participation événements culturels, sociaux ou communautaires"
label variable DUR902    "Durée - Activité de participation citoyenne (vote, fonction de juré)"
label variable DUR903    "Durée - Pratiques religieuses"
label variable DUR999    "Durée -Activités citoyennes, religieuses ou communautaires, non spéc."
label variable DUR1001   "Durée - Exercice"
label variable DUR1002   "Durée - Sports récréatifs organisés"
label variable DUR1004   "Durée - Sports de plein air (non compétitifs)"
label variable DUR1005   "Durée - Autres activités sportives"
label variable DUR1099   "Durée - Participation activités sportives, d'exercice, non spécifiées"
label variable DUR1101   "Durée - Aller au cinéma"
label variable DUR1102   "Durée - Assister à un concert ou événement de divertissement en direct"
label variable DUR1103   "Durée - Assister à un événement sportif"
label variable DUR1104   "Durée - Musées, galeries d'art, zoos, observatoires, parcs attractions"
label variable DUR1105   "Durée - Arts, loisirs ou jeux"
label variable DUR1106   "Durée - Loisirs ou activités de plein air"
label variable DUR1199   "Durée - Culture, passe-temps, loisirs ou plein air, non spécifié"
label variable DUR1201   "Durée - Lecture"
label variable DUR1202   "Durée - Regarder la télévision"
label variable DUR1203   "Durée - Écouter la musique, radio ou podcasts"
label variable DUR1204   "Durée - Utilisation de la technologie"
label variable DUR1299   "Durée - Activités liées aux médias de masse, non spécifiées"
label variable DUR1301   "Durée - Temps d'attente"
label variable DUR1302   "Durée - Temps libre, réfléchir, fumer"
label variable DUR1303   "Durée - Ne rien faire"
label variable DUR1304   "Durée - Autre activité"
label variable DUR9999   "Durée - Activité non spécifiée"
label variable DURS01    "Durée - Contact social - Seul"
label variable DURS02    "Durée - Contact social - Avec conjoint(e), partenaire"
label variable DURS03    "Durée - Contact social - Avec les enfants du ménage (<15 ans)"
label variable DURS04    "Durée - Contact social - Avec les enfants du ménage (15+ ans)"
label variable DURS05    "Durée - Contact social - Avec parents ou beaux-parents"
label variable DURS06    "Durée - Contact social - Avec d’autres membres du ménage adultes"
label variable DURS07    "Durée -Contact social - Autres membres de la famille d’un autre ménage"
label variable DURS08    "Durée - Contact social - Avec des amis"
label variable DURS09    "Durée - Contact social - Avec des collègues, amis d’école"
label variable DURS10    "Durée - Contact social - Avec d’autres personnes"
label variable DURS99    "Durée - Contact social - Non spécifié"
label variable DURL3300  "Durée - À la maison ou sur la propriété"
label variable DURL3301  "Durée - Au travail ou à l'école"
label variable DURL3302  "Durée - Voyage relié au travail"
label variable DURL3303  "Durée - À la maison de quelqu'un d'autre ou sur sa propriété"
label variable DURL3304  "Durée - Dans le voisinage"
label variable DURL3305  "Durée - En plein air"
label variable DURL3306  "Durée - À l'épicerie, autres magasins ou centre commercial"
label variable DURL3307  "Durée - Bibliothèque, musée, théâtre"
label variable DURL3308  "Durée - Centre ou terrain sportif ou aréna"
label variable DURL3309  "Durée - Restaurant, bar, club"
label variable DURL3310  "Durée - Lieu de culte"
label variable DURL3311  "Durée - Centre médical, clinique dentaire ou autre clinique de santé"
label variable DURL3312  "Durée - Autre endroit"
label variable DURL3313  "Durée - Transport - en voiture, camion ou fourgonnette - conducteur"
label variable DURL3314  "Durée - Transport - en voiture, camion ou fourgonnette - passager"
label variable DURL3315  "Durée - Transport - à pied"
label variable DURL3316  "Durée - Transport - le transport en commun"
label variable DURL3317  "Durée - Transport - avion"
label variable DURL3318  "Durée - Transport - à bicyclette"
label variable DURL3319  "Durée - Transport - motocyclette, scooter ou mobylette"
label variable DURL3320  "Durée - Transport - taxi, service de Limousine"
label variable DURL3323  "Durée - Transport - autre"
label variable DURL3399  "Durée - Transport, non spécifié"
label variable DURL9999  "Durée -  Localisation non spécifiée"
label variable TUT_970   "Jour de référence - Différent de la plupart"
label variable ADLTDUR   "Durée - Soins des adultes (ménage ou famille)"
label variable CHLDDUR   "Durée - Soins des enfants (<18) (ménage ou famille)"
label variable CIVICDUR  "Durée - Activités citoyennes, religieuses ou communautaires"
label variable FREEDUR   "Durée - Temps d'attente, temps libre, fumer, et ne rien faire"
label variable HELPDUR   "Durée - Bénévolat informel ou organisé et autre travail non rémunéré"
label variable HSWKDUR   "Durée - Tâches ménagères pour le ménage (inclus la famille)"
label variable LEISDUR   "Durée - Loisir actif, sports, culture et divertissement"
label variable MEALSDUR  "Durée - Manger ou boire"
label variable MEDIADUR  "Durée - Activités liées aux médias de masse"
label variable PDWKDUR   "Durée - Activités de travail rémunéré"
label variable PERSDUR   "Durée - Activités personnelles"
label variable SCHLDUR   "Durée - Éducation et activités apparentées"
label variable SHOPDUR   "Durée - Magasinage de biens ou de services"
label variable SLEEPDUR  "Durée - Activités du sommeil, se détendre et repos au lit"
label variable SLEEP1D   "Durée (en minutes) du sommeil la première nuit"
label variable SLEEP1S   "Début de la période de sommeil la première nuit"
label variable SLEEP2D   "Durée (en minutes) du sommeil la deuxième nuit"
label variable SLEEP2S   "Début de la période de sommeil la deuxième nuit"
label variable SOCDUR    "Durée - Socialiser et communiquer"
label variable SPRTSDUR  "Durée - Participation à des activités sportives et d'exercice physique"
label variable TRANSDUR  "Durée - Transport aller ou retour d’activité"
label variable OTHDUR    "Durée - Autres activités ou activités inconnues"
label variable TOTEPI    "Nombre total d'épisodes pendant la journée de référence"
label variable EPI101    "Nombre de périodes - Sommeil essentiel (de nuit ou de jour)"
label variable EPI102    "Nombre de périodes - Insomnie"
label variable EPI103    "Nombre de périodes - Sieste, repos, se reposer, se détendre"
label variable EPI104    "Nombre de périodes - Malade au lit, repos au lit ou de rééducation"
label variable EPI109    "Nombre de périodes - Sommeil/se détendre/repos au lit, non spécifié"
label variable EPI126    "Nombre de périodes - Soins personnels"
label variable EPI127    "Nombre de périodes - Soins médicaux auto-administrés"
label variable EPI128    "Nombre de périodes - Soins de santé professionnels, consultation"
label variable EPI129    "Nb.de périodes - Recevoir des soins pers. par un autre mem. du mén."
label variable EPI130    "Nombre de périodes - Recevoir des soins personnels par fournisseurs"
label variable EPI151    "Nombre de périodes - Manger"
label variable EPI152    "Nombre de périodes - Boire autrement qu'avec un repas ou une collation"
label variable EPI153    "Nombre de périodes -Pause ou repas lié aux activités de trav. rémunéré"
label variable EPI154    "Nombre de périodes - Pause ou repas lié aux études ou à l'apprenti."
label variable EPI159    "Nombre de périodes - Manger ou boire, non spécifié"
label variable EPI199    "Nombre de périodes - Soins personnels, non spécifiés"
label variable EPI201    "Nombre de périodes - Préparer ou servir les repas ou collations"
label variable EPI202    "Nombre de périodes - Nettoyage après les repas, laver la vaisselle"
label variable EPI203    "Nombre de périodes - Conservation de la nourriture"
label variable EPI204    "Nombre de périodes - Déballer l'épicerie"
label variable EPI205    "Nb.de périodes - Faire le ménage, s'occuper des plantes"
label variable EPI206    "Nombre de périodes - Sortir les poubelles/compost, déballage de biens"
label variable EPI207    "Nom. de périodes -Lavage, rapiécer, repasser, soins des souliers, etc."
label variable EPI208    "Nb.de pério. - Organi., planif. activi. mén., payer factu., courrier"
label variable EPI209    "Nombre de périodes - Soins des animaux de compagnie"
label variable EPI231    "Nombre de périodes - Coudre  (pour soi-même ou mén. ou fam.)"
label variable EPI232    "Nb.de pério. - Trav. d'entretiens intér. / réparation faits soi-même"
label variable EPI233    "Nombre de périodes - Installation, entretien / réparation chez soi"
label variable EPI234    "Nb.de périodes - Faire ou défaire les bagages pour  voyage / camping"
label variable EPI235    "Nom. de périodes -Emballer ou déballer les boîtes pour un déménagement"
label variable EPI236    "Nombre de périodes - Entretien extérieur"
label variable EPI237    "Nb.de pério. - Travaux extér.  ou réparation faits soi-même"
label variable EPI238    "Nombre de périodes - Construction faite soi-même"
label variable EPI239    "Nombre de périodes - Entretien et réparation d'un véhicule"
label variable EPI240    "Nombre de périodes - Ramasser, couper, corder du bois"
label variable EPI241    "Nb.de périodes-Jardinage, faire l’élevage d’animaux, etc., pour mén."
label variable EPI261    "Nombre de périodes - Magasinage de biens - en personne"
label variable EPI262    "Nombre de périodes - Magasinage de services - en personne"
label variable EPI263    "Nombre de périodes - Magasinage en ligne de biens ou services"
label variable EPI264    "Nombre de périodes - Recherche pour faire l'achat de biens ou services"
label variable EPI269    "Nombre de périodes - Magasinage, non spécifié"
label variable EPI299    "Nombre de périodes - Tâches ménagères (mén. ou famille), non spécifié"
label variable EPI301    "Nb.de périodes-Soins d'enfants (<15)(mén. ou fam.): Soins personnels"
label variable EPI302    "Nombre de périodes - Soins d'enfants (<15) (mén. ou fam.): Lire, jouer"
label variable EPI303    "Nombre de périodes - Soins d'enfants (<15) (mén. ou fam.): Éducatif"
label variable EPI304    "Nb.de périodes -Soins d'enfants (<15)(mén. ou fam.) : Accompagnement"
label variable EPI305    "Nb.de périodes -Soins d'ado (15-17)(mén. ou fam.) : Soins personnels"
label variable EPI306    "Nombre de périodes - Soins d'ado. (15-17) (mén. ou fam.) : Éducatif"
label variable EPI307    "Nb. de périodes - Soins d'ado (15-17) (mén. ou fam.) : Accompagnement"
label variable EPI351    "Nb. de périodes -Soins d'adulte (18+)(mén. ou fam.): Soins personnels"
label variable EPI352    "Nb. de périodes - Soins d'adulte (18+)(mén. ou fam.) : Accompagnement"
label variable EPI353    "Nb. De périodes -Soins d'adulte (18+)(mén. ou fam.): Tâches ménagères"
label variable EPI359    "Nb. de périodes - Soins d'adulte (18+) (mén. ou fam.), non spécifié"
label variable EPI399    "Nb. de pério. - Soins des enfants (<18) (mén. ou fam.), non spéci."
label variable EPI401    "Nb. de périodes - Transport pour recevoir soins perso. ou en revenir"
label variable EPI402    "Nb. de pério. Transpo. associé aux soins des enf. (<18) (mén.  fam.)"
label variable EPI403    "Nb. de pério. - Transpo. associé aux soins  (18 ans+) (mén. ou fam.)"
label variable EPI404    "Nom. de périodes - Transport pour aller ou revenir de manger ou boire"
label variable EPI405    "Nombre de périodes - Transport associé aux tâches ménagères régulières"
label variable EPI406    "Nom. de périodes-Transport associé aux tâches ménagères occasionnelles"
label variable EPI407    "Nb. de périodes - Transport- se rendre ou revenir d'un trav. rémunéré"
label variable EPI408    "Nombre de périodes - Transport liées aux études ou à l'apprentissage"
label variable EPI409    "Nombre de périodes - Transport -  se rendre ou revenir de magasiner"
label variable EPI410    "Nombre de périodes - Transport lié à la socialisation ou communication"
label variable EPI411    "Nombre de périodes - Transport bénévolat et autre travail non rémunéré"
label variable EPI412    "Nb. de périodes -Transport activités citoy., relig. ou communautaires"
label variable EPI413    "Nombre de périodes - Transport lié aux sports ou à l'exercice"
label variable EPI414    "Nb. de périodes - Transport - Activités cultur., événe. Sportifs"
label variable EPI415    "Nb. de périodes - Transport - Passe-temps, loisirs, activi. Extérieu."
label variable EPI416    "Nombre de périodes - Transport - Activités liées aux médias de masse"
label variable EPI499    "Nombre de périodes - Transport, non spécifié"
label variable EPI501    "Nombre de périodes - Travail rémunéré"
label variable EPI502    "Nombre de périodes - Formation rémunérée"
label variable EPI503    "Nombre de périodes - Attente ou inactivité liées au travail rémunéré"
label variable EPI504    "Nb. de périodes - Vente de biens/services contre rémuné. ou profit"
label variable EPI505    "Nombre de périodes - Autres activités générant des revenus"
label variable EPI506    "Nombre de périodes - Recherche d'emploi"
label variable EPI599    "Nb. de périodes - Trav. rémunéré et activités reliées, non specifiés"
label variable EPI601    "Nombre de périodes - Études à temps plein ou temps partiel - sur place"
label variable EPI602    "Nombre de périodes - Études à temps plein ou temps partiel - en ligne"
label variable EPI603    "Nombre de périodes - Travaux, devoirs, leçons ou recevoir du tutorat"
label variable EPI604    "Nb. de périodes - Cours dévelop. person., loisir, intérêt particulier"
label variable EPI699    "Nombre de périodes - Études ou apprentissage, non specifiés"
label variable EPI701    "Nombre de périodes - Socialiser ou communiquer - en personne"
label variable EPI702    "Nom. de périodes -Socialiser ou communiquer - en utilisant technologie"
label variable EPI799    "Nombre de périodes - Socialiser ou communiquer, non specifié"
label variable EPI801    "Nb. de périodes - Bénévolat (autre domicile., pas fam.) - Soins <18"
label variable EPI802    "Nb. de pério. -Bénévolat (autre domicile., pas fam.) - Soins d'adulte"
label variable EPI803    "Nb. de pério. - Bénévolat  (autre domicile., pas fam.) - tâches ména."
label variable EPI804    "Nb. de pério. - Bénévolat dans une entreprise d'un autre ménage"
label variable EPI805    "Nb. de pério. - Bénévolat : entraîneur, administrateur de sport"
label variable EPI806    "Nb. de pério. -Bénév. organisé  (non rémunéré, non obligatoire)"
label variable EPI807    "Nom. de périodes-Travail non rémunéré visant à améliorer la communauté"
label variable EPI808    "Nb. de périodes - Bénévolat exigé école, employeur, tribunal, autre"
label variable EPI899    "Nb. de pério. - Trav. non-rému. pas pour son domicile., non spécifié"
label variable EPI901    "Nombre de périodes - Participa. Événe. culturels, soc. ou communau."
label variable EPI902    "Nombre de périodes - Participation citoyenne (vote, fonction de juré)"
label variable EPI903    "Nombre de périodes - Pratiques religieuses"
label variable EPI999    "Nb. de périodes -Activ. citoyennes, relig. ou communau., non spéc."
label variable EPI1001   "Nombre de périodes - Exercice"
label variable EPI1002   "Nombre de périodes - Sports récréatifs organisés"
label variable EPI1004   "Nombre de périodes - Sports de plein air (non compétitifs)"
label variable EPI1005   "Nombre de périodes - Autres activités sportives"
label variable EPI1099   "Nb. de pério. -  Activités sportives, exercice, non spécifiées"
label variable EPI1101   "Nombre de périodes - Aller au cinéma"
label variable EPI1102   "Nb. de pério. - Assister à un concert ou divertissement en direct"
label variable EPI1103   "Nombre de périodes - Assister à un événement sportif"
label variable EPI1104   "Nb. de pério. -Musées, gale. d'art, zoos, observa., parcs attractions"
label variable EPI1105   "Nombre de périodes - Arts, loisirs ou jeux"
label variable EPI1106   "Nombre de périodes - Loisirs ou activités de plein air"
label variable EPI1199   "Nombre de périodes - Culture, passe-temps, loisirs, non spécifié"
label variable EPI1201   "Nombre de périodes - Lecture"
label variable EPI1202   "Nombre de périodes - Regarder la télévision"
label variable EPI1203   "Nombre de périodes - Écouter la musique, radio ou podcasts"
label variable EPI1204   "Nombre de périodes - Utilisation de la technologie"
label variable EPI1299   "Nom. de périodes -Activités liées aux médias de masse, non spécifiées"
label variable EPI1301   "Nombre de périodes - Temps d'attente"
label variable EPI1302   "Nombre de périodes - Temps libre, réfléchir, fumer"
label variable EPI1303   "Nombre de périodes - Ne rien faire"
label variable EPI1304   "Nombre de périodes - Autre activité"
label variable EPI9999   "Nombre de périodes - Activité non spécifiée"
label variable WTBS_001  "Pondération Bootstrap no 1 pour la pondération personnelle"
