label values   ACTIVITY  ACTIVITY_FMT
label values   DURATION  DURATION_FMT
label values   DUR_03    DUR_03_FMT
label values   ENDMIN    ENDMIN_FMT
label values   INSTANCE  INSTANCE_FMT
label values   LOCATION  LOCATION_FMT
label values   PUMFID    PUMFID_FMT
label values   STARTMIN  STARTMIN_FMT
label values   TUI_01    TUI_01_FMT
label values   TUI_03    TUI_03_FMT
label values   TUI_06A   TUI_06A_FMT
label values   TUI_06B   TUI_06B_FMT
label values   TUI_06C   TUI_06C_FMT
label values   TUI_06D   TUI_06D_FMT
label values   TUI_06E   TUI_06E_FMT
label values   TUI_06F   TUI_06F_FMT
label values   TUI_06G   TUI_06G_FMT
label values   TUI_06H   TUI_06H_FMT
label values   TUI_06I   TUI_06I_FMT
label values   TUI_06J   TUI_06J_FMT
label values   TUI_07    TUI_07_FMT
label values   TUI_15    TUI_15_FMT
