label variable PUMFID    "Numéro d’identification de l’enregistrement du FMGD"
label variable INSTANCE  "Numéro séquentiel de chaque épisode"
label variable WGHT_EPI  "Pondération de la période"
label variable ACTIVITY  "Activité principale"
label variable DUR_03    "Durée de l'activité simultanée"
label variable DURATION  "Durée d'un épisode (en minutes)"
label variable ENDMIN    "Heure de la fin de l'épisode en minutes"
label variable ENDTIME   "Heure de la fin de l'épisode"
label variable INSTANCE  "Numéro séquentiel de chaque épisode"
label variable LOCATION  "Localisation de la période"
label variable STARTIME  "Heure du début de l'épisode"
label variable STARTMIN  "Temps du début de l'épisode en minutes"
label variable TUI_01    "Activité principale - codes détaillés"
label variable TUI_03    "Activité simultanée"
label variable TUI_06A   "Contact social - Seul(e)"
label variable TUI_06B   "Contact social - Avec conjoint(e) ou partenaire"
label variable TUI_06C   "Contact social - Avec enfants du ménage ayant moins de 15 ans"
label variable TUI_06D   "Contact social - Avec enfants du ménage, 15 ans et plus"
label variable TUI_06E   "Contact social - Avec le(s) parent(s) ou beau(x)-parent(s)"
label variable TUI_06F   "Contact social- Avec le(s) autre(s) membre(s) du ménage adulte(s)"
label variable TUI_06G   "Contact social- Avec autre(s) membre(s) de la famille-autre ménage"
label variable TUI_06H   "Contact social - Avec ami(e/s)"
label variable TUI_06I   "Contact social - Avec les collègues, ami(e/s) d’école"
label variable TUI_06J   "Contact social - Avec autre personne(s)"
label variable TUI_07    "Utilisation des technologies du répondant"
label variable TUI_15    "Échelle de bien-être subjectif"
label variable WEPI_001  "Pondération Bootstrap no 1 pour la pondération au niveau des épisodes"
