label variable PUMFID    "PUMF Record identification"
label variable WGHT_PER  "Person weight"
label variable SURVMNTH  "Survey month of data collection"
label variable EQFLAG    "Survey collection mode"
label variable PRV       "Province of residence"
label variable LUC_RST   "Population centres indicator"
label variable REGION    "Region of residence of the respondent"
label variable HSDSIZEC  "Household size of respondent (capped)"
label variable AGEGR10   "Age group of respondent (groups of 10)"
label variable GENDER2   "Gender (2) after distribution of the non-binary persons"
label variable MARSTAT   "Marital status of the respondent"
label variable PHSDFLG   "Respondent has a spouse/partner in the household"
label variable AGEPRC    "Age group of respondent’s spouse/partner (collapsed)"
label variable GENPR2    "Gender of spouse/partner after distribution of the non-binary person"
label variable COUPGEN2  "Gender+ of household couple"
label variable CHH0017C  "Number of child(ren) in household - 0 to 17 years (capped)"
label variable CHH0004C  "Child(ren) in household - 0 to 4 years (flag)"
label variable CHH0514C  "Child(ren) in household - 5 to 14 years (flag)"
label variable CHH1517C  "Child(ren) in household - 15-17 years (flag)"
label variable CXRFLAG   "Child(ren) of respondent living in household"
label variable PARNUM    "Number of parents the respondent has in household"
label variable SENFLAG   "Senior(s) (age 65 and over) in household"
label variable MULTIGEN  "Three generations or more in the respondent’s household"
label variable DDEV_FL   "Disability indicator - Developmental"
label variable DDEX_FL   "Disability indicator - Dexterity"
label variable DFLEX_FL  "Disability indicator - Flexibility"
label variable DHEAR_FL  "Disability indicator - Hearing"
label variable DLRN_FL   "Disability indicator - Learning"
label variable DMEM_FL   "Disability indicator - Memory"
label variable DMENT_FL  "Disability indicator - Mental health-related"
label variable DMOB_FL   "Disability indicator - Mobility"
label variable DPAIN_FL  "Disability indicator - Pain-related"
label variable DUNK_FL   "Disability indicator - Unknown disability"
label variable DVIS_FL   "Disability indicator - Seeing"
label variable DDIS_FL   "Disability status"
label variable DTYPER    "Disability type counter - Grouped"
label variable DCLASS    "Global (disability) severity class"
label variable TCS_110   "Perceptions of time - Plans to slow down"
label variable TCS_120   "Perceptions of time - Workaholic"
label variable TCS_130   "Perceptions of time - Tends to cut back on sleep"
label variable TCS_140   "Perceptions of time - Not accomplishing what you set out to do"
label variable TCS_150   "Perceptions of time - Not spending enough time with family or friends"
label variable TCS_160   "Perceptions of time - Constantly under stress"
label variable TCS_170   "Perceptions of time - Trapped in daily routine"
label variable TCS_180   "Perceptions of time - No time for fun"
label variable TCS_190   "Perceptions of time - Stress when there is not enough time"
label variable TCS_200   "Perceptions of time - Would like more time alone"
label variable TIMECR    "Time crunch indicator"
label variable UH_01     "Unpaid service - Looking after children from your household"
label variable UH_02     "Unpaid service - Looking after children from other households"
label variable UH_03     "Unpaid service - Household chores for your household"
label variable UH_04     "Unpaid service - Household chores for other households"
label variable UH_05     "Unpaid service - Care of seniors in your household"
label variable UH_06     "Unpaid service - Care of seniors from other households"
label variable CHLD_01C  "Childcare - Weekday - Physical care (collapsed)"
label variable CHLD_02C  "Childcare - Weekday - School related (collapsed)"
label variable CHLD_03C  "Childcare - Weekday - Leisure activities (collapsed)"
label variable CHLD_04C  "Childcare - Weekday - Accompanies (collapsed)"
label variable CHLD_05C  "Childcare - Weekend - Physical care (collapsed)"
label variable CHLD_06C  "Childcare - Weekend - School related (collapsed)"
label variable CHLD_07C  "Childcare - Weekend - Leisure activities (collapsed)"
label variable CHLD_08C  "Childcare - Weekend - Accompanies (collapsed)"
label variable LSM_01    "Subjective well-being"
label variable GEN_01    "Self rated health"
label variable GEN_02    "Self rated mental health"
label variable SRS_10    "Self Rated Stress - Amount"
label variable MSS_130   "Main Source of Stress"
label variable ACT7DAYC  "Main activity - Last week (collapsed)"
label variable MRW_05C   "Main activity - Last 12 months (collapsed)"
label variable MRW_D40A  "Worked in the last 12 months"
label variable MRW_D40B  "Worked last week"
label variable WET_120   "Job type during weeks employed"
label variable WHW_110   "More than one paid job last week"
label variable WHW_230   "Usual work schedule at main job"
label variable WHWD140G  "Hours worked at all jobs in a week (grouped)"
label variable TLWK_01A  "Telework last week - From home"
label variable TLWK_01B  "Telework last week - Co-working space"
label variable TLWK_01C  "Telework last week - Other location"
label variable TLWK_01D  "Telework last week - Did not do any teleworking last week"
label variable TLWK_02G  "Telework last week - Paid hours (grouped)"
label variable TLWK_03   "Preferred amount of teleworking in work schedule"
label variable TLWK_04   "Telework aspects - Organize own working hours"
label variable TLWK_05   "Telework aspects - Video conferencing"
label variable TLWK_06   "Telework aspects - Avoid the commute"
label variable TLWK_07   "Telework aspects - Reduce business trips"
label variable TLWK_08   "Telework aspects - Time with family or pets"
label variable TLWK_09   "Reason for not teleworking in the last week"
label variable WLYD170G  "Distance from residence to workplace (grouped)"
label variable NAIC22CY  "NAICS 2022 (20 categories) - Last year"
label variable NOCLBR_Y  "NOC 21 (10 categories) - Last year (the variant)"
label variable WFS_10    "Work flexible schedule"
label variable SRC_10    "Satisfaction with current balance between job and home life"
label variable SRC_20A   "Dissatisfaction - Job/home - Not enough time for family"
label variable SRC_20B   "Dissatisfaction - Job/home - Spends too much time on job/main activity"
label variable SRC_20C   "Dissatisfaction - Job and home - Not enough time for other activities"
label variable SRC20EGR  "Dissatisfaction - Job/home - Employment related reasons (grouped)"
label variable SRC_20F   "Dissatisfaction - Job/home - Health reasons"
label variable SRC20HGR  "Dissatisfaction - Job/home - Other reasons (grouped)"
label variable WLB_10    "Work-life balance - Difficulty because of the job - 12 months"
label variable WLB_20    "Work-life balance - Difficulty because of family - 12 months"
label variable HRH_10A   "Hires paid help - None"
label variable HRH_10B   "Hires paid help - Child care"
label variable HRH_10C   "Hires paid help - House cleaning"
label variable HRH_10D   "Hires paid help - Outdoor work"
label variable HRH_10E   "Hires paid help - Medical help"
label variable HRH_10F   "Hires paid help - Other"
label variable ATT_120   "Vehicle at respondent's disposal"
label variable ATT_130   "Need someone else to drive - Frequency"
label variable ATT_131   "Someone else can drive when needed - Frequency"
label variable ATT_140A  "Can drive when needed - Family member living with respondent"
label variable ATT_140B  "Can drive when needed - Family member not living with respondent"
label variable ATT_140C  "Can drive when needed - Friend"
label variable ATT_140D  "Can drive when needed - Neighbour"
label variable ATT_140E  "Can drive when needed - Organization or agency"
label variable ATT_150C  "Most common kind of transportation - Typical week (collapsed)"
label variable ATT_160   "Access to public transportation"
label variable ATT_170   "Use of public transportation - Past 12 months"
label variable ATT_180A  "Did not use public transportation - You have a car"
label variable ATT_180B  "Did not use public transportation - Close enough to walk or bike"
label variable ATT_180C  "Did not use public transportation - Concern for personal health"
label variable ATT_180D  "Did not use public transportation - Stops are too far away"
label variable ATT_180E  "Did not use public transportation - Schedule is too inconvenient"
label variable ATT_180F  "Did not use public transportation - Routes do not go where you want"
label variable ATT_180G  "Did not use public transportation - Disabilities prevent use"
label variable ATT_180I  "Did not use public transportation - Have access to parking at work"
label variable ATT_180J  "Did not use public transportation - Concern for personal safety"
label variable CTW_140A  "Commute to work/school - Car, truck or van - As driver"
label variable CTW_140B  "Commute to work/school - Car, truck or van - As passenger"
label variable CTW_140C  "Commute to work/school - Public transit"
label variable CTW_140D  "Commute to work/school - Walked"
label variable CTW_140E  "Commute to work/school - By bicycle"
label variable CTW140GR  "Commute to work/school - Other (grouped)"
label variable CTW_140I  "Commute to work/school - Worked/Attended school at home"
label variable CTW_150G  "Commute to work/school - Length of time one way (grouped)"
label variable CTW_160   "Commute to work/school - Ever used public transit"
label variable CTW_170   "Commute to work/school - Convenience of public transit (user)"
label variable CTW_180   "Commute to work/school - Convenience of public transit (non-user)"
label variable CTW_190   "Commute to work/school - Traffic congestion (frequency)"
label variable CTW_210   "Commute to work/school - Satisfaction with commute time"
label variable CTW_215   "Commute to work - Traffic congestion (seriousness)"
label variable ED_05     "Educational attainment - Highest degree (7 categories)"
label variable EDC_10    "Education - School Attendance"
label variable MAP_110C  "Main activity - Spouse/partner - 12 months (collapsed)"
label variable MAP_D40A  "Spouse/partner - worked in the last 12 months"
label variable DOR_110C  "Dwelling type (collapsed)"
label variable IM_01A    "Born in/outside Canada - Respondent"
label variable YRARRI_C  "Year respondent first came to Canada to live (collapsed)"
label variable BPP_01A   "Place of birth of respondent's spouse/partner - Canada"
label variable BPR_20    "Parents born in or outside of Canada"
label variable ABM_01A   "Indigenous Identity - Not First Nations, Métis or Inuk (Inuit)"
label variable AIP_01A   "Indigenous identity of spouse/partner - Not Indigenous"
label variable VISMINFL  "Visible minority flag"
label variable VISPRFL   "Visible minority status - Respondent’s spouse/partner"
label variable REL_02    "Frequency of religious participation - Past 12 months"
label variable REL_03    "Frequency of religious participation - On one’s own - 12 months"
label variable RELIGFLG  "Religious affiliation flag"
label variable LAN_01    "Knowledge of official languages (English and French)"
label variable LANCHC    "Mother tongue (collapsed)"
label variable LANHSDC   "Language spoken most often at home (collapsed)"
label variable INC_C     "Income - Total (before tax) (grouped)"
label variable FAMINC_C  "Family income - Total (before tax) (grouped)"
label variable GTU_110   "General time use - Feel rushed"
label variable GTU_130   "General time use - Extra time"
label variable UOT_01    "Satisfaction with use of time"
label variable DDAY      "Diary - Reference day"
label variable DVTDAY    "Diary - Reference day - Type"
label variable DIARYREC  "Recall period for completed diaries"
label variable DUR101    "Duration - Essential sleep (night or day)"
label variable DUR102    "Duration - Sleeplessness, insomnia"
label variable DUR103    "Duration - Naps, lying down, resting, relaxing"
label variable DUR104    "Duration - Sick in bed, bed or rehabilitative rest, convalescence"
label variable DUR109    "Duration - Sleep/relaxing/bed rest, unspecified"
label variable DUR126    "Duration - Personal care"
label variable DUR127    "Duration - Self-administered medical care"
label variable DUR128    "Duration - Health professional visit, consultation"
label variable DUR129    "Duration - Receiving personal care from another household member"
label variable DUR130    "Duration - Receiving personal care from other personal care providers"
label variable DUR151    "Duration - Eating"
label variable DUR152    "Duration - Drinking other than with meals or snacks"
label variable DUR153    "Break or lunch related to paid work activities"
label variable DUR154    "Duration - Break or lunch related to studying or learning"
label variable DUR159    "Duration - Eating or drinking, unspecified"
label variable DUR199    "Duration - Own personal care, unspecified"
label variable DUR201    "Duration - Preparing or serving meals or snacks"
label variable DUR202    "Duration - Food (or meal) cleanup, dish washing"
label variable DUR203    "Duration - Preserving foods"
label variable DUR204    "Duration - Unpacking groceries"
label variable DUR205    "Duration - Indoor house cleaning, tidying, care of house plants"
label variable DUR206    "Duration - Taking out garbage, recycling, compost, unpacking of goods"
label variable DUR207    "Duration - Laundry, mending, ironing, shoe care, etc."
label variable DUR208    "Duration - Organizing, planning, paying bills, managing mail"
label variable DUR209    "Duration - Pet care"
label variable DUR231    "Duration - Sewing clothes (for self or hhld. or fam.)"
label variable DUR232    "Duration - Interior do-it-yourself improvement, maintenance"
label variable DUR233    "Duration - Installation, servicing or repair of household goods"
label variable DUR234    "Duration - Packing or unpacking for a trip or camping"
label variable DUR235    "Duration - Packing or unpacking for a move of the household"
label variable DUR236    "Duration - Outdoor cleaning"
label variable DUR237    "Duration - Exterior D.I.Y. improvement, maintenance, home repair"
label variable DUR238    "Duration - Do-it-yourself construction"
label variable DUR239    "Duration - Vehicle maintenance or repairs"
label variable DUR240    "Duration - Harvesting, stacking or cutting firewood"
label variable DUR241    "Duration - Gardening, raising animals, etc., for hhld. use"
label variable DUR261    "Duration - In-person shopping for goods"
label variable DUR262    "Duration - In-person shopping for services"
label variable DUR263    "Duration - Online shopping for goods or services"
label variable DUR264    "Duration - Researching for purchasing goods or services"
label variable DUR269    "Duration - Shopping, unspecified"
label variable DUR299    "Duration - Unpaid household work (hhld. or family), unspecified"
label variable DUR301    "Duration - Childcare (<15) (hhld. or fam.): Personal care"
label variable DUR302    "Duration - Childcare (<15) (hhld. or fam.): Read, play, talk"
label variable DUR303    "Duration - Childcare (<15) (hhld. or fam.): Educational"
label variable DUR304    "Duration - Childcare (<15) (hhld. or fam.): Accompanying"
label variable DUR305    "Duration - Childcare (15-17) (hhld. or fam.): Personal care"
label variable DUR306    "Duration - Childcare (15-17) (hhld. or fam.): Educational"
label variable DUR307    "Duration - Childcare (15-17) (hhld. or fam.): Accompanying"
label variable DUR351    "Duration - Adult care (18+) (hhld. or fam.): Personal care"
label variable DUR352    "Duration - Adult care (18+) (hhld. or fam.): Accompanying"
label variable DUR353    "Duration - Adult care (18+) (hhld. or fam.): Household chores"
label variable DUR359    "Duration - Care of adults (18+) (hhld. or family), unspecified"
label variable DUR399    "Duration - Care of children (<18) (hhld. or family), unspecified"
label variable DUR401    "Duration - Travel to or from receiving personal care"
label variable DUR402    "Duration - Travel related to caring for children (<18) (hhld. or fam.)"
label variable DUR403    "Duration - Travel related to caring for adults (18+) (hhld. or fam.)"
label variable DUR404    "Duration - Travel to or from eating or drinking"
label variable DUR405    "Duration - Travel related to regular household tasks"
label variable DUR406    "Duration - Travel related to occasional household tasks"
label variable DUR407    "Duration - Travel to or from paid work activities"
label variable DUR408    "Duration - Travel to or from studying or learning activities"
label variable DUR409    "Duration - Travel to or from shopping"
label variable DUR410    "Duration - Travel to or from socializing or communicating activities"
label variable DUR411    "Duration - Travel to or from informal or org.-based volunteering"
label variable DUR412    "Duration - Travel to or from civic/religious/community activities"
label variable DUR413    "Duration - Travel to or from sports participation or physical exerise"
label variable DUR414    "Duration - Travel to or from culture or sports events"
label variable DUR415    "Duration - Travel to or from hobbies, leisure, outdoor activities"
label variable DUR416    "Duration - Travel related to mass media activities"
label variable DUR499    "Duration - Travel, unspecified"
label variable DUR501    "Duration - Paid work"
label variable DUR502    "Duration - Paid training"
label variable DUR503    "Duration - Waiting or idle time related to paid work activities"
label variable DUR504    "Duration - Selling of goods or services for pay or profit"
label variable DUR505    "Duration - Other income-generating activities"
label variable DUR506    "Duration - Looking for work"
label variable DUR599    "Duration - Paid work activities, unspecified"
label variable DUR601    "Duration - Schooling full time or part time - on site"
label variable DUR602    "Duration - Schooling full time or part time - online"
label variable DUR603    "Duration - Homework, studying or being tutored"
label variable DUR604    "Duration - Self development, leisure or special interest classes"
label variable DUR699    "Duration - Studying or learning, unspecified"
label variable DUR701    "Duration - Socializing or communicating - in person"
label variable DUR702    "Duration - Socializing or communicating - using any type of technology"
label variable DUR799    "Duration - Socializing or communicating, unspecified"
label variable DUR801    "Duration - Unpaid help (other hhlds, non-fam) - childcare (<18)"
label variable DUR802    "Duration - Unpaid help (other hhlds, non-fam) - caring for an adult"
label variable DUR803    "Duration - Unpaid help (other hhlds, non-fam) - doing chores"
label variable DUR804    "Duration - Unpaid work in enterprises owned by other households"
label variable DUR805    "Duration - Unpaid coaching or administering sports"
label variable DUR806    "Duration - Organization-based volunteering (unpaid, non-compulsory)"
label variable DUR807    "Duration - Unpaid work aimed at improving the community"
label variable DUR808    "Duration - Unpaid work required by school, employer, court or other"
label variable DUR899    "Duration - Unpaid work not for own household, unspecified"
label variable DUR901    "Duration - Participating in community, cultural or social events"
label variable DUR902    "Duration - Civic participation (voting, jury duty)"
label variable DUR903    "Duration - Religious practices"
label variable DUR999    "Duration - Civic, religious or community activities, unspecified"
label variable DUR1001   "Duration - Exercising"
label variable DUR1002   "Duration - Organized recreational sports"
label variable DUR1004   "Duration - Outdoor sports (non-competitive)"
label variable DUR1005   "Duration - Other sports activities"
label variable DUR1099   "Duration - Sports participation and physical exercise, unspecified"
label variable DUR1101   "Duration - Attending cinema"
label variable DUR1102   "Duration - Attending a concert or live entertainment event"
label variable DUR1103   "Duration - Attending sporting events"
label variable DUR1104   "Duration - Museums, galleries, zoos, observatories, amusement parks"
label variable DUR1105   "Duration - Arts, hobbies or playing games"
label variable DUR1106   "Duration - Leisure or outdoor activities"
label variable DUR1199   "Duration - Culture, hobbies, leisure, outdoor activities, unspecified"
label variable DUR1201   "Duration - Reading"
label variable DUR1202   "Duration - Watching television"
label variable DUR1203   "Duration - Listening to music, radio or podcasts"
label variable DUR1204   "Duration - Use of technology"
label variable DUR1299   "Duration - Mass media activities, unspecified"
label variable DUR1301   "Duration - Waiting time"
label variable DUR1302   "Duration - Free time, thinking, smoking"
label variable DUR1303   "Duration - Doing nothing"
label variable DUR1304   "Duration - Other activities"
label variable DUR9999   "Duration - Activity unspecified"
label variable DURS01    "Duration - Social Contact - Alone"
label variable DURS02    "Duration - Social Contact - With spouse, partner"
label variable DURS03    "Duration - Social Contact - With household children (<15 years)"
label variable DURS04    "Duration - Social Contact - With household children (15+ years)"
label variable DURS05    "Duration - Social Contact - With parents or parents-in-law"
label variable DURS06    "Duration - Social Contact - With other household adults"
label variable DURS07    "Duration - Social Contact - Other family members from other households"
label variable DURS08    "Duration - Social Contact - With friends"
label variable DURS09    "Duration - Social Contact - With colleagues or classmates"
label variable DURS10    "Duration - Social Contact - With other people"
label variable DURS99    "Duration - Social Contact - Not stated"
label variable DURL3300  "Duration - At home or on property"
label variable DURL3301  "Duration - At place of work or school"
label variable DURL3302  "Duration - Away on business"
label variable DURL3303  "Duration - At someone else's home or property"
label variable DURL3304  "Duration - In the neighbourhood"
label variable DURL3305  "Duration - Outdoors"
label variable DURL3306  "Duration - Grocery store, other stores or mall"
label variable DURL3307  "Duration - Library, museum or theatre"
label variable DURL3308  "Duration - Sports centre, field or arena"
label variable DURL3309  "Duration - Restaurant, bar or club"
label variable DURL3310  "Duration - Place of worship"
label variable DURL3311  "Duration - Medical, dental or other health clinic"
label variable DURL3312  "Duration - Elsewhere"
label variable DURL3313  "Duration - Travel - Car, truck or van - as driver"
label variable DURL3314  "Duration - Travel - Car, truck or van - as passenger"
label variable DURL3315  "Duration - Travel - Walk"
label variable DURL3316  "Duration - Travel - Public transit"
label variable DURL3317  "Duration - Travel - Airplane"
label variable DURL3318  "Duration - Travel - Bicycle"
label variable DURL3319  "Duration - Travel - Motorcycle, scooter or moped"
label variable DURL3320  "Duration - Travel - Taxi, Limousine Service"
label variable DURL3323  "Duration - Travel - Other"
label variable DURL3399  "Duration - Travel, not stated"
label variable DURL9999  "Duration - Location unspecified"
label variable TUT_970   "Reference day - Different than most"
label variable ADLTDUR   "Duration - Care of adults (hhld. or family)"
label variable CHLDDUR   "Duration - Care of children (<18) (hhld. or family)"
label variable CIVICDUR  "Duration - Civic or religious activities, or community social events"
label variable FREEDUR   "Duration - Waiting time, free time, smoking, and doing nothing"
label variable HELPDUR   "Duration - Informal or org.-based volunteering and other unpaid work"
label variable HSWKDUR   "Duration - Unpaid household work (hhld. or family)"
label variable LEISDUR   "Duration - Active leisure, sports, culture and entertainment"
label variable MEALSDUR  "Duration - Eating or drinking"
label variable MEDIADUR  "Duration - Mass media activities"
label variable PDWKDUR   "Duration - Paid work activities"
label variable PERSDUR   "Duration - Personal activities"
label variable SCHLDUR   "Duration - Education and related activities"
label variable SHOPDUR   "Duration - Shopping for goods and services"
label variable SLEEPDUR  "Duration - Sleep activities, relaxing, and bed rest"
label variable SLEEP1D   "Sleep duration (in minutes) the first night"
label variable SLEEP1S   "Start of sleep episode the first night"
label variable SLEEP2D   "Sleep duration (in minutes) the second night"
label variable SLEEP2S   "Start of sleep episode the second night"
label variable SOCDUR    "Duration - Socializing and communicating"
label variable SPRTSDUR  "Duration - Sports participation and physical exercise"
label variable TRANSDUR  "Duration - Transportation to or from activities"
label variable OTHDUR    "Duration - Other or unknown activities"
label variable TOTEPI    "Total number of episodes during the reference day"
label variable EPI101    "Occurrences - Essential sleep (night or day)"
label variable EPI102    "Occurrences - Sleeplessness, insomnia"
label variable EPI103    "Occurrences - Naps, lying down, resting, relaxing"
label variable EPI104    "Occurrences - Sick in bed, bed or rehabilitative rest, convalescence"
label variable EPI109    "Occurrences - Sleep/relaxing/bed rest, unspecified"
label variable EPI126    "Occurrences - Personal care"
label variable EPI127    "Occurrences - Self-administered medical care"
label variable EPI128    "Occurrences - Health professional visit, consultation"
label variable EPI129    "Occurrences - Receiving personal care from another household member"
label variable EPI130    "Occurrences - Receiving personal care from other providers"
label variable EPI151    "Occurrences - Eating"
label variable EPI152    "Occurrences - Drinking other than with meals or snacks"
label variable EPI153    "Occurrences - Break or lunch related to paid work activities"
label variable EPI154    "Occurrences - Break or meal related to studying or learning"
label variable EPI159    "Occurrences - Eating or drinking, unspecified"
label variable EPI199    "Occurrences - Own personal care, unspecified"
label variable EPI201    "Occurrences - Preparing or serving meals or snacks"
label variable EPI202    "Occurrences - Food (or meal) cleanup, dish washing"
label variable EPI203    "Occurrences - Preserving foods"
label variable EPI204    "Occurrences - Unpacking groceries"
label variable EPI205    "Occurrences - Indoor house cleaning, tidying, care of house plants"
label variable EPI206    "Occurrences - Taking out garbage/recycling/compost, unpacking goods"
label variable EPI207    "Occurrences - Laundry, mending, ironing, shoe care, etc."
label variable EPI208    "Occurrences - Organizing, planning, paying bills, managing mail"
label variable EPI209    "Occurrences - Pet care"
label variable EPI231    "Occurrences - Sewing clothes (for self or hhld. or fam.)"
label variable EPI232    "Occurrences - Interior do-it-yourself improvement, maintenance"
label variable EPI233    "Occurrences - Installation, servicing or repair of household goods"
label variable EPI234    "Occurrences - Packing or unpacking for a trip or camping"
label variable EPI235    "Occurrences - Packing or unpacking for a move of the household"
label variable EPI236    "Occurrences - Outdoor cleaning"
label variable EPI237    "Occurrences - Exterior D.I.Y. improvement, maintenance, home repair"
label variable EPI238    "Occurrences - Do-it-yourself construction"
label variable EPI239    "Occurrences - Vehicle maintenance or repairs"
label variable EPI240    "Occurrences - Harvesting, stacking or cutting firewood"
label variable EPI241    "Occurrences - Gardening, raising animals, etc., for hhld. use"
label variable EPI261    "Occurrences - In-person shopping for goods"
label variable EPI262    "Occurrences - In-person shopping for services"
label variable EPI263    "Occurrences - Online shopping for goods or services"
label variable EPI264    "Occurrences - Researching for purchasing goods or services"
label variable EPI269    "Occurrences - Shopping, unspecified"
label variable EPI299    "Occurrences - Unpaid household work (hhld. or family), unspecified"
label variable EPI301    "Occurrences - Childcare (<15) (hhld. or fam.): Personal care"
label variable EPI302    "Occurrences - Childcare (<15) (hhld. or fam.): Read, play, talk"
label variable EPI303    "Occurrences - Childcare (<15) (hhld. or fam.): Educational"
label variable EPI304    "Occurrences - Childcare (<15) (hhld. or fam.): Accompanying"
label variable EPI305    "Occurrences - Childcare (15-17) (hhld. or fam.): Personal care"
label variable EPI306    "Occurrences - Childcare (15-17) (hhld. or fam.): Educational"
label variable EPI307    "Occurrences - Childcare (15-17) (hhld. or fam.): Accompanying"
label variable EPI351    "Occurrences - Adult care (18+) (hhld. or fam.): Personal care"
label variable EPI352    "Occurrences - Adult care (18+) (hhld. or fam.): Accompanying"
label variable EPI353    "Occurrences - Adult care (18+) (hhld. or fam.): Household chores"
label variable EPI359    "Occurrences - Care of adults (18+) (hhld. or family), unspecified"
label variable EPI399    "Occurrences - Care of children (<18) (hhld. or family), unspecified"
label variable EPI401    "Occurrences - Travel to or from receiving personal care"
label variable EPI402    "Occurrences - Travel related to caring for child (<18) (hhld. or fam.)"
label variable EPI403    "Occurrences -Travel related to caring for adults (18+) (hhld. or fam.)"
label variable EPI404    "Occurrences - Travel to or from eating or drinking"
label variable EPI405    "Occurrences - Travel related to regular household tasks"
label variable EPI406    "Occurrences - Travel related to occasional household tasks"
label variable EPI407    "Occurrences - Travel to or from paid work activities"
label variable EPI408    "Occurrences - Travel to or from studying or learning activities"
label variable EPI409    "Occurrences - Travel to or from shopping"
label variable EPI410    "Occurrences -Travel to or from socializing or communicating activities"
label variable EPI411    "Occurrences - Travel to or from informal or org.-based volunteering"
label variable EPI412    "Occurrences - Travel to or from civic/religious/community activities"
label variable EPI413    "Occurrences - Travel to or from sports participation, physical exerise"
label variable EPI414    "Occurrences - Travel to or from culture or sports events"
label variable EPI415    "Occurrences - Travel to or from hobbies, leisure, outdoor activities"
label variable EPI416    "Occurrences - Travel related to mass media activities"
label variable EPI499    "Occurrences - Travel, unspecified"
label variable EPI501    "Occurrences - Paid work"
label variable EPI502    "Occurrences - Paid training"
label variable EPI503    "Occurrences - Waiting or idle time related to paid work activities"
label variable EPI504    "Occurrences - Selling of goods or services for pay or profit"
label variable EPI505    "Occurrences - Other income-generating activities"
label variable EPI506    "Occurrences - Looking for work"
label variable EPI599    "Occurrences - Paid work activities, unspecified"
label variable EPI601    "Occurrences - Schooling full time or part time - on site"
label variable EPI602    "Occurrences - Schooling full time or part time - online"
label variable EPI603    "Occurrences - Homework, studying or being tutored"
label variable EPI604    "Occurrences - Self development, leisure or special interest classes"
label variable EPI699    "Occurrences - Studying or learning, unspecified"
label variable EPI701    "Occurrences - Socializing or communicating - in person"
label variable EPI702    "Occurrences - Socializing or communicating - using technology"
label variable EPI799    "Occurrences - Socializing or communicating, unspecified"
label variable EPI801    "Occurrences - Unpaid help (other hhlds, non-fam) - childcare (<18)"
label variable EPI802    "Occurrences - Unpaid help (other hhlds, non-fam) - caring for an adult"
label variable EPI803    "Occurrences - Unpaid help (other hhlds, non-fam) - doing chores"
label variable EPI804    "Occurrences - Unpaid work in enterprises owned by other households"
label variable EPI805    "Occurrences - Unpaid coaching or administering sports"
label variable EPI806    "Occurrences - Organization-based volunteering (unpaid, non-compulsory)"
label variable EPI807    "Occurrences - Unpaid work aimed at improving the community"
label variable EPI808    "Occurrences -Unpaid work required by school, employer, court or other"
label variable EPI899    "Occurrences - Unpaid work not for own household, unspecified"
label variable EPI901    "Occurrences - Participating in community, cultural or social events"
label variable EPI902    "Occurrences - Civic participation (voting, jury duty)"
label variable EPI903    "Occurrences - Religious practices"
label variable EPI999    "Occurrences - Civic, religious or community activities, unspecified"
label variable EPI1001   "Occurrences - Exercising"
label variable EPI1002   "Occurrences - Organized recreational sports"
label variable EPI1004   "Occurrences - Outdoor sports (non-competitive)"
label variable EPI1005   "Occurrences - Other sports activities"
label variable EPI1099   "Occurrences - Sports participation and physical exercise, unspecified"
label variable EPI1101   "Occurrences - Attending cinema"
label variable EPI1102   "Occurrences - Attending a concert or live entertainment event"
label variable EPI1103   "Occurrences - Attending sporting events"
label variable EPI1104   "Occurrences - Museums, galleries, zoos, observatories, amusement parks"
label variable EPI1105   "Occurrences - Arts, hobbies or playing games"
label variable EPI1106   "Occurrences - Leisure or outdoor activities"
label variable EPI1199   "Occurrences - Culture, hobby, leisure, outdoor activities, unspecified"
label variable EPI1201   "Occurrences - Reading"
label variable EPI1202   "Occurrences - Watching television"
label variable EPI1203   "Occurrences - Listening to music, radio or podcasts"
label variable EPI1204   "Occurrences - Use of technology"
label variable EPI1299   "Occurrences - Mass media activities, unspecified"
label variable EPI1301   "Occurrences - Waiting time"
label variable EPI1302   "Occurrences - Free time, thinking, smoking"
label variable EPI1303   "Occurrences - Doing nothing"
label variable EPI1304   "Occurrences - Other activities"
label variable EPI9999   "Occurrences - Activity unspecified"
label variable WTBS_001  "Bootstrap weight # 1 for personal weight"
