format
    ACTIVITY                  D00083FF.
    DURATION                  M00840FF.
    DUR_03                    A00708FF.
    ENDMIN                    M00839FF.
    ENDTIME                  $M00839FF.
    INSTANCE                  M00077FF.
    LOCATION                  D00085FF.
    PUMFID                    M00087FF.
    STARTIME                 $M00839FF.
    STARTMIN                  M00839FF.
    TUI_01                    D00140FF.
    TUI_03                    D00141FF.
    TUI_06A                   YESN01FF.
    TUI_06B                   YESN01FF.
    TUI_06C                   YESN01FF.
    TUI_06D                   YESN01FF.
    TUI_06E                   YESN01FF.
    TUI_06F                   YESN01FF.
    TUI_06G                   YESN01FF.
    TUI_06H                   YESN01FF.
    TUI_06I                   YESN01FF.
    TUI_06J                   YESN01FF.
    TUI_07                    YESN01FF.
    TUI_15                    A00709FF.
    WEPI_001                  M00835FF.
    WGHT_EPI                  M00834FF.
    ;
