format
    ACTIVITY                  D00083FE.
    DURATION                  M00840FE.
    DUR_03                    A00708FE.
    ENDMIN                    M00839FE.
    ENDTIME                  $M00839FE.
    INSTANCE                  M00077FE.
    LOCATION                  D00085FE.
    PUMFID                    M00087FE.
    STARTIME                 $M00839FE.
    STARTMIN                  M00839FE.
    TUI_01                    D00140FE.
    TUI_03                    D00141FE.
    TUI_06A                   YESN01FE.
    TUI_06B                   YESN01FE.
    TUI_06C                   YESN01FE.
    TUI_06D                   YESN01FE.
    TUI_06E                   YESN01FE.
    TUI_06F                   YESN01FE.
    TUI_06G                   YESN01FE.
    TUI_06H                   YESN01FE.
    TUI_06I                   YESN01FE.
    TUI_06J                   YESN01FE.
    TUI_07                    YESN01FE.
    TUI_15                    A00709FE.
    WEPI_001                  M00835FE.
    WGHT_EPI                  M00834FE.
    ;
